databases:
  - name: david
    databaseName: david_6vls
    user: david_6vls_user

services:
  - type: web
    name: okpah
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: david_6vls
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false